import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Link } from 'react-router-dom';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay } from 'swiper/modules';
//images
import logo from '@/assets/images/logo.png';
// style
import 'swiper/swiper-bundle.css';
const AuthLayout = ({ pageImage, title, helpText, bottomLinks, children, starterClass }) => {
    return (_jsxs("div", { className: "flex items-stretch h-screen bg-cover bg-center relative bg-no-repeat  bg-[url('../images/bg-auth.jpg')]", children: [_jsx("div", { className: "lg:max-w-[480px] z-10 p-12 relative w-full h-full border-t-[3px] border-primary bg-white", children: _jsxs("div", { className: "flex flex-col h-full gap-4", children: [_jsx("div", { className: "mb-8 text-center lg:text-start", children: _jsx(Link, { to: "/", className: "flex justify-center", children: _jsx("img", { src: logo, alt: "logo", className: "h-20 block" }) }) }), _jsxs("div", { className: `my-auto ${starterClass ? 'text-center' : ''}`, children: [pageImage && _jsx("img", { src: pageImage, alt: "", className: "rounded-full shadow h-16 mx-auto" }), _jsx("h4", { className: `text-lg font-semibold text-light/80 mb-2 ${pageImage ? 'mt-6' : ''}`, children: title }), _jsx("p", { className: "text-gray-400 mb-9", children: helpText }), children] }), bottomLinks] }) }), _jsx("div", { className: "bg-black/30 w-full h-full relative hidden lg:block", children: _jsx("div", { className: "absolute start-0 end-0 bottom-0 flex mt-auto justify-center text-center", children: _jsx("div", { className: "xl:w-1/2 w-full mx-auto", children: _jsx("div", { className: "swiper mt-auto cursor-col-resize", id: "swiper_one", children: _jsx("div", { className: "swiper-wrapper mb-12", children: _jsxs(Swiper, { spaceBetween: 50, slidesPerView: 1, modules: [Autoplay], loop: true, autoplay: { delay: 5000 }, children: [_jsx(SwiperSlide, { children: _jsxs("div", { className: "swiper-slide-content", children: [_jsx("h2", { className: "text-3xl text-white mb-6", children: "Da el paso a la tecnologia!" }), _jsxs("p", { className: "text-lg text-white mb-5", children: [_jsx("i", { className: "ri-double-quotes-l" }), " La tecnolog\u00EDa nos facilita reducir las barreras de la distancia y el tiempo."] }), _jsx("p", { className: "text-white mx-auto", children: "- CEO LowSolutions" })] }) }), _jsx(SwiperSlide, { children: _jsxs("div", { className: "swiper-slide-content", children: [_jsx("h2", { className: "text-3xl text-white mb-6", children: "Flexibilidad !" }), _jsxs("p", { className: "text-lg text-white mb-5", children: [_jsx("i", { className: "ri-double-quotes-l" }), " Gracias a este sistema pude mejorar el rendimiento de mi negocio."] }), _jsx("p", { className: "text-white mx-auto", children: "- Usuario" })] }) }), _jsx(SwiperSlide, { children: _jsxs("div", { className: "swiper-slide-content", children: [_jsx("h2", { className: "text-3xl text-white mb-6", children: "Actualizaciones Frecuentes!" }), _jsxs("p", { className: "text-lg text-white mb-5", children: [_jsx("i", { className: "ri-double-quotes-l" }), " El sistema se encuentra con actualizaciones frecuentes y soporte al cliente 24/7."] }), _jsx("p", { className: "text-white mx-auto", children: "- Equipo De Desarrollo" })] }) })] }) }) }) }) }) })] }));
};
export default AuthLayout;
