import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PopoverLayout from './HeadlessUI/PopoverLayout';
//image
import avatar2 from '@/assets/images/users/avatar-2.jpg';
import avatar5 from '@/assets/images/users/avatar-5.jpg';
const TopBarSearch = () => {
    const PopoverToggler = () => {
        return (_jsxs(_Fragment, { children: [_jsx("input", { type: "search", className: "form-input bg-black/5 border-none ps-8 relative", placeholder: "Search..." }), _jsx("span", { className: "ri-search-line text-base z-10 absolute start-2 top-1/2 -translate-y-1/2" })] }));
    };
    return (_jsx(_Fragment, { children: _jsx(PopoverLayout, { placement: "bottom-start", toggler: _jsx(PopoverToggler, {}), children: _jsxs("div", { className: "mt-5 w-80 z-50 transition-all duration-300 bg-white shadow-lg border rounded-lg py-2 border-gray-200 dark:border-gray-700 dark:bg-gray-800", children: [_jsxs("h5", { className: "flex items-center py-2 px-3 text-sm text-gray-800 dark:text-gray-400 uppercase", children: ["Found ", _jsx("b", { className: "text-decoration-underline", children: " \u00A008\u00A0" }), " results"] }), _jsxs(Link, { to: "#", className: "flex items-center py-2 px-3 text-sm text-gray-800 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300", onClick: () => {
                            console.info('search was clicked');
                        }, children: [_jsx("i", { className: "ri-file-chart-line text-base me-1" }), _jsx("span", { children: "Analytics Report" })] }), _jsxs(Link, { to: "#", className: "flex items-center py-2 px-3 text-sm text-gray-800 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300", children: [_jsx("i", { className: "ri-lifebuoy-line text-base me-1" }), _jsx("span", { children: "How can I help you?" })] }), _jsxs(Link, { to: "#", className: "flex items-center py-2 px-3 text-sm text-gray-800 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300", children: [_jsx("i", { className: "ri-user-settings-line text-base me-1" }), _jsx("span", { children: "User profile settings" })] }), _jsx("h6", { className: "flex items-center py-2 px-3 text-sm text-gray-800 dark:text-gray-400 uppercase", children: "Users" }), _jsxs(Link, { to: "#", className: "flex items-center py-2 px-3 text-sm text-gray-800 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300", children: [_jsx("img", { className: "me-2 rounded-full h-8", src: avatar2, alt: "Generic placeholder image" }), _jsxs("div", { className: "flex-grow", children: [_jsx("h5", { className: "m-0 fs-14", children: "Erwin Brown" }), _jsx("span", { className: "fs-12 ", children: "UI Designer" })] })] }), _jsxs(Link, { to: "#", className: "flex items-center py-2 px-3 text-sm text-gray-800 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300", children: [_jsx("img", { className: "me-2 rounded-full h-8", src: avatar5, alt: "Generic placeholder image" }), _jsxs("div", { className: "flex-grow", children: [_jsx("h5", { className: "m-0 fs-14", children: "Jacob Deo" }), _jsx("span", { className: "fs-12 ", children: "Developer" })] })] })] }) }) }));
};
export default TopBarSearch;
